FROM ubuntu:22.04
RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
    && sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
    && apt-get update \
    && apt-get install unzip wget gcc make libpng-dev imagemagick -y \
    && apt-get install libsdl1.2-dev libsdl-image1.2-dev libhpdf-dev -y \
    && rm -rf /var/lib/apt/lists/* \
    && wget https://githubfast.com/scott-wong/PrinterToPDF/archive/refs/heads/master.zip \
    && unzip master.zip \
    && rm -rf master.zip \
    && cd PrinterToPDF-master \
    && make && make install
WORKDIR /opt
CMD ["bash"]
